### ISSUE TITLE
Maybe avoid generating endpoints next to routes

### ISSUE THREAD

**Issue by pixelmund** [pixelmund/svemix#50]
### Describe the bug

The situation is a bit tricky, we're currently using/generating SvelteKit Endpoints next to the files, but this can quickly sum up to a lot of files. I don't know if there is a way to avoid generating them while still using the functionality. This should probably belong to Kit, but i'm not sure what a solution in Kit would look like.

- I've already tried using different techniques with the handle hook, but all seem wrong.
- I've also experimented and looked into if we could solve this with our vite plugin. 
- Maybe allowing multiple route paths in Kit would help with this issue?

We could also leave it the way it is currently.

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

We shouldn't create the endpoints visible to the user.

### Screenshots or Videos

-

### Platform

-

### Additional context

-

**Comment by Acmion** [comment]
Yeah, I have also thought about this issue. 

I hid the "unwanted" files in VS Code, however, this is not generalizable to all cases. Additionally, this is also relatively prone to errors, especially if working in teams where a member may edit a generated file and thus causing problems in the long run.

**Comment by pixelmund** [comment]
A temporary solution is to edit the vscode settings or create a `/.vscode/settings.json` file with the following content:

```json
{
    "files.exclude": {
        "src/routes/**/*.ts": true,
        "src/routes/**/*.js": true,
        "src/routes/api/**/*.js": false,
        "src/routes/api/**/*.ts": false
    }
}
``` 

The api folder would contain anything that you wan't to handle with Standalone SvelteKit and yes @Acmion this is unfortunate.

**Comment by wobsoriano** [comment]
Tbf I dont think there’s another way of doing this with sveltekit

**Comment by wobsoriano** [comment]
Remix added support for Vue, and now have an open PR for Svelte fyi

https://github.com/brophdawg11/remix-routers/pull/9

**Comment by MirrorBytes** [comment]
Would it be possible to leverage virtual modules in a cache for dev?
